/* eslint-disable @typescript-eslint/no-array-constructor */
type supportsActiveX = 'Native' | 'NPWrap' | 'NPPGWrap' | 'Unsupported';

type MSNChatParamNames =
  | 'AuditMessage'
  | 'BackColor'
  | 'BackHighlightColor'
  | 'BaseURL'
  | 'ButtonBackColor'
  | 'ButtonFrameColor'
  | 'ButtonTextColor'
  | 'Category'
  | 'ChannelLanguage'
  | 'ChatHome'
  | 'ChatMode'
  | 'CreateRoom'
  | 'CreationModes'
  | 'Feature'
  | 'HexRoomName'
  | 'InputBorderColor'
  | 'InvitationCode'
  | 'Locale'
  | 'Market'
  | 'MessageOfTheDay'
  | 'MSNProfile'
  | 'MSNREGCookie'
  | 'NickName'
  | 'NicknameToInvite'
  | 'PassportProfile'
  | 'PassportTicket'
  | 'ResDLL'
  | 'RoomName'
  | 'Server'
  | 'SubscriberInfo'
  | 'TopBackHighlightColor'
  | 'Topic'
  | 'UpsellURL'
  | 'URLBack'
  | 'UserRole'
  | 'WelcomeMsg'
  | 'WhisperContent';

type MSNChatParams = [name: MSNChatParamNames, value: string];
type MSNChatFrameType = MSNChatParams[];

// @ts-expect-error Browser polyfill for globalThis
if (typeof globalThis == 'undefined') const globalThis = window;

function getActiveXSupport(): supportsActiveX {
  let supportsActiveX: supportsActiveX = 'Unsupported';

  if (typeof globalThis.navigator != 'undefined') {
    if (
      globalThis.navigator.appName == 'Microsoft Internet Explorer' || // IE3-10
      (typeof (globalThis as any).ScriptEngine != 'undefined' && (globalThis as any).ScriptEngine() == 'JScript') // IE4-11
      // IE3+
    ) {
      if (typeof globalThis.navigator.platform != 'undefined') {
        // IE4+
        if (globalThis.navigator.platform == 'Win32') {
          // IE4+, Win32
          supportsActiveX = 'Native';
        }
      } else {
        // IE3
        if (parseInt(globalThis.navigator.appVersion) == 2) {
          // Not IE3 for Mac (where appVersion is 3)
          if (
            typeof globalThis.navigator.userAgent != 'undefined' &&
            globalThis.navigator.userAgent.indexOf('Windows 3.') == -1
          ) {
            // IE3, Win32 (not Win16)
            supportsActiveX = 'Native';
          }
        }
      }
    } else if (typeof globalThis.navigator.plugins != 'undefined') {
      if (
        typeof (globalThis.navigator.plugins as any)['Microsoft ActiveX Portability Container (NPPGWrap)'] !=
        'undefined'
      ) {
        supportsActiveX = 'NPPGWrap';
      } else if (
        typeof (globalThis.navigator.plugins as any)['Microsoft ActiveX Portability Container (NPWrap)'] != 'undefined'
      ) {
        supportsActiveX = 'NPWrap';
      } else {
        supportsActiveX = 'Unsupported'; // Unknown - It may work with the NPAPI plugin
      }
    }
  }
  return supportsActiveX;
}

function _DOMLoaded() {
  if (__runOnce != true) return;
  __runOnce = null; // GC
  const hasActiveXSupport = getActiveXSupport();
  if (hasActiveXSupport != 'Unsupported') {
    getNickname(hasActiveXSupport);
    //createChatFrame('test', hasActiveXSupport);
  }
}

function getNickname(hasActiveXSupport: supportsActiveX) {
  const nicknameHTML =
    '<!DOCTYPE html><html><head><title>Mono Chat</title></head><body>' +
    '<script>' +
    // This following function was generated by the TS below
    'function createChatFrame(e,t){var i=new Array(new Array("BaseURL","http://www.mono.chat/legacy/"),new Array("NickName",e),new Array("RoomName","The Lobby"),new Array("Server","dir.irc7.com"));var n="<!DOCTYPE html><html><head><title>Mono Chat</title><style>html,body{padding:0;margin:0;height:100%;}</style></head><body>";if(t=="Native"){n+=\'<object classid="clsid:F58E1CEF-A068-4c15-BA5E-587CAF3EE8C6" codebase="http://msnld.com/msnchat45.cab#Version=9,02,0310,2401" width="100%" height="100%">\'}else{n+=\'<embed controlclassid="F58E1CEF-A068-4c15-BA5E-587CAF3EE8C6" height="100%" width="100%" npcodebase="./nppgwrap.cab#Version=8,0,0,1" \'+\'controlcodebase="http://web.archive.org/web/20150622204452if_/http://fdl.msn.com/public/chat/msnchat45.cab#Version=9,02,0310,2401" \'+\'type="application/x-\'+t.toLowerCase()+\'"\'}for(var a=0;a<i.length;a++){if(t=="Native"){n+=\'<param name="\'+i[a][0]+\'" value="\'+i[a][1]+\'">\'}else{n+=" "+i[a][0]+\'="\'+i[a][1]+\'"\'}}if(t=="Native"){n+="</object>"}else{n+="/>"}n+="</body></html>";document.write(n);document.close()}' +
    // Prevents null nickname, passes ActiveXSupport to createChatFrame
    'function setNickname(x,t){if(x=="")x="null";createChatFrame(x,t);}' +
    '</script>' +
    '<form onsubmit="setNickname(this.nn.value, \'' +
    hasActiveXSupport +
    '\');return false;">' +
    '<label for="nn">Nickname:</label><br>' +
    '<input type="text" id="nn" name="nn"><input type="submit" value="Join"></form>' +
    '</body></html>';
  document.write(nicknameHTML);
  document.close();
}

// function createChatFrame(nickname: string, activeXSupport: supportsActiveX) {
//   const ChatFrame = new Array(
//     new Array('BaseURL', 'http://www.mono.chat/legacy/'),
//     new Array('NickName', nickname),
//     new Array('RoomName', 'The Lobby'),
//     new Array('Server', 'dir.irc7.com')
//   ) as MSNChatFrameType;

//   let chatFrameHTML =
//     '<!DOCTYPE html><html><head><title>Mono Chat</title><style>html,body{padding:0;margin:0;height:100%;}</style></head><body>';
//   if (activeXSupport == 'Native') {
//     chatFrameHTML +=
//       '<object classid="clsid:F58E1CEF-A068-4c15-BA5E-587CAF3EE8C6" ' +
//       'codebase="http://web.archive.org/web/20150622204452if_/http://fdl.msn.com/public/chat/msnchat45.cab#Version=9,02,0310,2401" ' +
//       'width="100%" height="100%">';
//   } else {
//     chatFrameHTML +=
//       '<embed controlclassid="F58E1CEF-A068-4c15-BA5E-587CAF3EE8C6" height="100%" width="100%" npcodebase="./nppgwrap.cab#Version=8,0,0,1" ' +
//       'controlcodebase="http://web.archive.org/web/20150622204452if_/http://fdl.msn.com/public/chat/msnchat45.cab#Version=9,02,0310,2401" ' +
//       'type="application/x-' +
//       activeXSupport.toLowerCase() +
//       '"';
//   }
//   for (let i = 0; i < ChatFrame.length; i++) {
//     if (activeXSupport == 'Native') {
//       chatFrameHTML += '<param name="' + ChatFrame[i][0] + '" value="' + ChatFrame[i][1] + '">';
//     } else {
//       chatFrameHTML += ' ' + ChatFrame[i][0] + '="' + ChatFrame[i][1] + '"';
//     }
//   }
//   if (activeXSupport == 'Native') {
//     chatFrameHTML += '</object>';
//   } else {
//     chatFrameHTML += '/>';
//   }
//   chatFrameHTML += '</body></html>';
//   document.write(chatFrameHTML);
//   document.close();
// }

let __runOnce = true;
if (typeof globalThis.document != 'undefined' && typeof globalThis.document.addEventListener != 'undefined') {
  document.addEventListener('DOMContentLoaded', _DOMLoaded);
}
